---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - testing-library
  - jest-dom
  - react

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/react'
  - 'plugin:jest-dom/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  no-console: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  import/no-extraneous-dependencies: off
  react/jsx-uses-vars:
    - error
  react/jsx-uses-react:
    - error
  testing-library/prefer-screen-queries: off
  testing-library/no-render-in-setup: ["error", {"allowTestingFrameworkSetupHook": "beforeEach"}]
